### PR TITLE
[Fixes #214] User ember-cli-babel’s public API to discover config (pl…

### LINKED ISSUE #214: @babel/plugin-proposal-class-properties issue
An app that functions without embroider enabled, currently fails when embroider is enabled when `classProperties` are used.  

```js
Build Error (PackagerRunner) in app.js:7

/private/var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/embroider/2e1ac4/app.js: Support for the experimental syntax 'classProperties' isn't currently enabled (7:16):

   5 |
   6 | class App extends Application {
>  7 |   modulePrefix = config.modulePrefix;
     |                ^
   8 |   podModulePrefix = config.podModulePrefix;
   9 |   Resolver = Resolver;
  10 | }

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.


Stack Trace and Error Report: /var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/error.dump.33e3fb7de16d52c299f3b39be89e429c.log
```

```js
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: app.js
    - line: 7
    - treeDir: [undefined]
  - message: app.js:7: /private/var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/embroider/2e1ac4/app.js: Support for the experimental syntax 'classProperties' isn't currently enabled (7:16):

   5 | 
   6 | class App extends Application {
>  7 |   modulePrefix = config.modulePrefix;
     |                ^
   8 |   podModulePrefix = config.podModulePrefix;
   9 |   Resolver = Resolver;
  10 | }
```
Interesting files:
* [Error Log](https://gist.github.com/stefanpenner/e6e8e0f71c2f03095178f6d8eb29f3fa)
* [_babel_config_.js](https://gist.github.com/stefanpenner/ec59bb84d455d24c1580875af88c2161)

### PR DESCRIPTION
**Pull request by stefanpenner**
…ugins/preset)

- [x] verified in offending app
- [x] confirm with @ef4 
- [x] make tests green

### CODE REVIEW

File: packages/compat/src/v1-app.ts [hunk 1]
```diff
@@ -184,55 +183,35 @@ export default class V1App implements V1Package {
...
+    });
 
-    // this is reproducing what ember-cli-babel does. It would be nicer to just
-    // call it, but it require()s all the plugins up front, so not serializable.
-    // In its case, it's mostly doing it to set basedir so that broccoli caching
-    // will be happy, but that's irrelevant to us here.
+    let plugins = babelConfig.plugins as any[];
+    let presets = babelConfig.presets;
+
+    // install embroider macros
```
Comment (ef4) [inline packages/compat/src/v1-app.ts]: This comment is wrong. `debugMacrosPlugin` is a stock ember-cli, it's not related to embroider macros.

File: packages/compat/src/v1-app.ts [hunk 2]
```diff
@@ -184,55 +183,35 @@ export default class V1App implements V1Package {
...
-        // even if the app was using @embroider/macros, we drop it from the config
-        // here in favor of our globally-configured one.
-        return (
-          !isEmbroiderMacrosPlugin(p) &&
-          // similarly, if the app was already using
-          // ember-cli-htmlbars-inline-precompile, we remove it here because we
-          // have our own always-installed version of that (v2 addons are
-          // allowed to assume it will be present in the final app build, the
-          // app doesn't get to turn that off or configure it.).
-          !TemplateCompiler.isInlinePrecompilePlugin(p)
```
Comment (ef4) [inline packages/compat/src/v1-app.ts]: We can't just drop this filtering. It's incorrect for either `@embroider/macros` or `hbs` to run in stage1. 

If `@embroider/macros` run here it will do so with the wrong configuration.

If `hbs` runs here, we will lose visibility into component and template dependencies that come from within those `hbs` templates.

**Comment by stefanpenner** [comment]
> Is the idea here that we just give up on babel config serializability?

The config should be serializable: 

* https://github.com/babel/ember-cli-babel/blob/95d7c73fb0ff0b1aa029411e315c93efa5989a35/index.js#L358
* https://github.com/babel/ember-cli-babel/blob/95d7c73fb0ff0b1aa029411e315c93efa5989a35/index.js#L358
* etc

File: packages/compat/src/v1-app.ts (hunk 1 above)
Comment (stefanpenner) [reply packages/compat/src/v1-app.ts]: oops

File: packages/compat/src/v1-app.ts (hunk 2 above)
Comment (stefanpenner) [reply packages/compat/src/v1-app.ts]: Oops, removing this was actually by mistake. Good catch. I guess i screwed up a rebase or something.

**Comment by ef4** [comment]
Ah, thanks. I went looking at this has indeed already been fixed for quite a while. I think the original commit was https://github.com/babel/ember-cli-babel/commit/a2c478474401e04b0702d61feba7d43f2c94ecd2

So that's good then, I'm glad to use the real API.

**Comment by stefanpenner** [comment]
@ef4 ya, ensuring these are serializable in ember-cli-babel is important, so it has been fixed. Likely just after you made your adaptation here.

@ef4 do you mind if I merge? If you do, let me know what I can work to address said concerns.

File: packages/compat/src/v1-app.ts [hunk 3]
```diff
@@ -184,55 +183,48 @@ export default class V1App implements V1Package {
...
-        );
-      });
-    }
+    const babelAddon = (this.app.project as any).findAddonByName('ember-cli-babel');
+    const babelConfig = babelAddon.buildBabelOptions({
+      'ember-cli-babel': {
+        includeExternalHelpers: true,
+        compileModules: false,
+        disableDebugTooling: true,
```
Comment (stefanpenner) [inline packages/compat/src/v1-app.ts]: I think we needed this to be false not true...
