### PR TITLE
`@embroider/router` Ember 4 CI job compatibility

### LINKED ISSUE #1024: `@embroider/router ember-release` job fails due to ember-auto-import v1
With the release of Ember 4 ember-auto-import v2 is now required. It seems that the `@embroider/router` addon still has [v1 listed as a devDependency ](https://github.com/embroider-build/embroider/blob/bec54e21af303b07a600c4c220ccb3032d5f4619/packages/router/package.json#L47)which means [the "release" jobs fail in CI](https://github.com/embroider-build/embroider/runs/4243114985?check_suite_focus=true).

I think we can just bump the ember-auto-import dependency in that package without requiring v2 in consuming apps since it's a devDependency?

### LINKED ISSUE #1028: `@embroider/router` addon blueprint isn't compatible with Ember 4
It seems #1024 was only a symptom of a bigger issue. The addon blueprint itself hasn't been updated with ember-cli-update which means it will require some changes to make it compatible with the ember-release job.

### PR DESCRIPTION
**Pull request by Windvis**
This updates the blueprint to the latest version and adds some other changes to make the tests succeed on Ember v4.

Closes #1024 
Closes #1028

### CODE REVIEW

**Comment by simonihmig** [comment]
@Windvis I enabled CI for your PR. It looks fine to me, but one test related to your (refactored!) `used-in-child` component is failing in the classic scenario! 🤔

File: packages/router/tests/acceptance/lazy-routes-test.js [hunk 1]
```diff
@@ -6,65 +6,92 @@ import { getGlobalConfig } from '@embroider/macros';
...
-    return Boolean(requirejs.entries[`${ENV.modulePrefix}/templates/${routeName}`]);
+    return Boolean(
+      requirejs.entries[`${ENV.modulePrefix}/templates/${routeName}`]
+    );
   }
 
-  function hasComponentTemplate(name) {
-    return Boolean(requirejs.entries[`${ENV.modulePrefix}/templates/components/${name}`]);
+  function hasComponent(name) {
+    return Boolean(requirejs.entries[`${ENV.modulePrefix}/components/${name}`]);
```
Comment (Windvis) [inline packages/router/tests/acceptance/lazy-routes-test.js:31]: @simonihmig I updated the path and renamed the function. Should be good now! :pray:

**Comment by ef4** [comment]
Thanks, nice work.
